apiVersion: v1
kind: Namespace
metadata:
  name: hazelcast
---
apiVersion: v1
kind: Service
metadata:
  namespace: hazelcast
  labels:
    name: hazelcast
  name: hazelcast
spec:
  ports:
    - port: 5701
  selector:
    name: hazelcast
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: hazelcast
  name: hazelcast
  labels:
    name: hazelcast
spec:
  template:
    metadata:
      labels:
        name: hazelcast
    spec:
      containers:
      - name: hazelcast
        livenessProbe:
          exec:
            command:
            - /opt/hazelcast/health_check.sh
          initialDelaySeconds: 60
          timeoutSeconds: 1
        image: gcr.io/endpoints-jenkins/hazelcast
        imagePullPolicy: Always
        env:
        - name: JAVA_OPT
          value: "-Xms1024M -Xmx8192M"
        ports:
        - containerPort: 5701
        resources:
          limits:
            memory: 9Gi
