apiVersion: v1
kind: Namespace
metadata:
  name: hazelcast
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: hazelcast
  name: hazelcast
  labels:
    name: hazelcast
spec:
  replicas: 4
  template:
    metadata:
      labels:
        name: hazelcast
    spec:
      containers:
      - name: hazelcast
        image: quay.io/pires/hazelcast-kubernetes:0.7.0
        imagePullPolicy: Always
        env:
        - name: "POD_NAMESPACE"
          value: "hazelcast"
        - name: "DNS_DOMAIN"
          value: "cluster.local"
        ports:
        - name: hazelcast
          containerPort: 5701
---
apiVersion: v1
kind: Service
metadata:
  namespace: hazelcast
  labels:
    name: hazelcast
  name: hazelcast
spec:
  ports:
    - port: 5701
  selector:
    name: hazelcast
